[project]
name = "llm-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.99.6",
    "lark>=1.1.9",
    "pytest>=8.0",
]

[project.scripts]
llm-playground = "cli:main"
